config/routes.rb
Empregos::Application.routes.draw do
	get "usuarios/new"

	get "usuarios/create"

	get "tags/index"

	get "tags/show"
	
	get "/busca" => 'pages#search', :as => :search

  get "session/new"
	get "/vagas/para/:perfil" =>'vagas#index', :as=>'vagas_para'
	get "/meus_dados" => 'empresas#meusdados', :as=>'meus_dados'
  resources :empresas do
		resources :perfis do
			resources :vagas		
		end
  end

	resources :usuarios
	resources :tags
	resources :vagas
	resources :sessions

	match '/home' => 'pages#home', :as=>'home'
	get '/anunciar' =>'vagas#new', :as => 'anunciar'

	match "/log_out" => "sessions#destroy", :as => "log_out"
	match "/log_in" => "sessions#new", :as => "log_in"
	match "/log_in_anunciar" => "sessions#create_anunciar", :as => "log_in_anunciar"

   root :to => "pages#home"

end

app/views/pages/_barrahorizontal.html.erb
<div id="centro_barra">
	<div id="busca">
		<%= form_tag('/busca', :method=>"get") do %>
			<div class="searchBox round">
					<%= text_field_tag :term, nil, :class=>"term" %>
					<%= submit_tag 'Pesquisar', :class=>"search" %>
				<div class="clear">
				</div>
			</div>
		<% end %>

	</div>

	<div id="anunciar">	
		Gostaria de anunciar?
		Clique <%= link_to 'aqui', anunciar_path %>, e rapido e simples
	</div>
</div>

app/views/pages/_cabecalho.html.erb
<div id="centro_cabecalho">
	<div id="logo">
		<h1>
			<%= link_to (image_tag 'logo.png', :alt=>"Logo"), root_url %>
		</h1>	
	</div>
	<div id="nav_bar" class="round">
		<ul>			
			<li><%= link_to 'Home', root_url %></li>
			<li><%= link_to 'Anunciar', anunciar_url,:class=>'borda' %></li>
			<li><a href="como_funciona.html" class="borda">Como Funciona</a></li>

				<% if current_user %>
					<li><%= link_to 'Meus Dados', meus_dados_path, :class=>'borda' %></li>
					<li><%= link_to 'LogOut', log_out_path,:class=>'borda' %></li>
				<% else %>
					<li><%= link_to 'Login', log_in_path, :class=>'borda' %></li>
				<% end %>
			</li>					
		</ul>				
	</div>

	<div class="clear"></div>
</div>
<div id="barra_horizontal">
	<%= render :partial=>"pages/barrahorizontal" %>
</div>

app/views/pages/_cadastrorapido.html.erb
<h1>Cadastre-se e receba Notícias</h1><div class="clear"></div>
<%= form_tag('/usuarios') do -%>
	<p><%= label_tag 'email', 'E-mail' %>
		<% if notice %>
			<%= text_field_tag :email, notice, :class=>"dados erro" %>
		<% else %>
			<%= text_field_tag :email, nil, :class=>"dados" %>
		<% end %>
	</p>
	<p>
		<%= label_tag 'area', 'Área' %>
	 	<%= select_tag "areas", options_from_collection_for_select(Area.all, "id", "nome"),
	      :multiple => true, :size=>5, :class => 'dados' %>
	</p>
   <p><%= submit_tag 'Salvar', :class=>"botao" %></p>
<% end -%>

<div id="info">
	Voce receberá noticias sobre as vagas 
	mais recentes e as vagas que possam lhe interessar.
</div>

app/views/pages/_estatisticas.html.erb
<h1>Estatisticas</h1>
<ul>
	<% Perfil.all.each do |p| %>
		<% if p.vagas.size > 0 %>
			<% if p.nome=="Todos" %>
			<li>	<%= "#{pluralize(p.vagas.size, "vaga")} para"%>
					<%= link_to " #{p.nome} Perfis", vagas_para_path(p) %> </li>
			<% else %>
			<li>	<%= "#{pluralize(p.vagas.size, "vaga")} para"%>
					<%= link_to " #{p.nome}", vagas_para_path(p) %> </li>
			<% end %>
		<% end %>
	<% end %>
	<li><%= link_to "Ver todas vagas (#{Vaga.all.size})", vagas_path %></li>
</ul>

app/views/pages/_lateral.html.erb
<div id="cadastre-se" class="round">
	<%= render 'pages/cadastrorapido' %>
</div>
<div id="estatisticas">
	<%= render 'pages/estatisticas' %>
</div>

app/views/pages/_rodape.html.erb
<div id="footer" class="round">
	<div id="menu">
		<ul>
			<li><a href="#">Sobre</a></li>
			<li><a href="#">Ajuda</a></li>
			<li><a href="#">Contato</a></li>
		</ul>
	</div>
	<div id="copyright">
		<span>
			© 2010 - 2011 
		</span>
			<a href="http://www.softsystems-corp.com">SoftSystems Corp</a>
	</div>
</div>

app/views/pages/home.html.erb
<div id="conteudo"> 
	<h1 class="vagas_recentes">Vagas cadastradas mais recentemente</h1>

	<%= render @vagas %>

</div>
<div id="lateral">
	<%= render 'pages/lateral' %>
</div>
<div class="clear">
</div>

app/views/pages/search.html.erb
<div id="vagas"> 
	<h1 class="vagas_recentes">Vagas para <%= params[:term]%></h1>
	<p class="paginacao">
		<%= paginate @vagas%>
	</p>
		<% if @vagas.size > 0 %>
			<%=render @vagas %>
		<% else %>
			<p class="vaga_nao_encontrada">Desculpe, nenhuma vaga relacionada foi encontrada!!!</p>
			<p class="vaga_nao_encontrada_info">Por favor, tente outro nome.</p>
		<% end %>

	<p class="paginacao">
		<%= paginate @vagas %>
	</p>
</div>