config/routes.rb
Empregos::Application.routes.draw do
	get "usuarios/new"

	get "usuarios/create"

	get "tags/index"

	get "tags/show"
	
	get "/busca" => 'pages#search', :as => :search

  get "session/new"
	get "/vagas/para/:perfil" =>'vagas#index', :as=>'vagas_para'
	get "/meus_dados" => 'empresas#meusdados', :as=>'meus_dados'
  resources :empresas do
		resources :perfis do
			resources :vagas		
		end
  end

	resources :usuarios
	resources :tags
	resources :vagas
	resources :sessions

	match '/home' => 'pages#home', :as=>'home'
	get '/anunciar' =>'vagas#new', :as => 'anunciar'

	match "/log_out" => "sessions#destroy", :as => "log_out"
	match "/log_in" => "sessions#new", :as => "log_in"
	match "/log_in_anunciar" => "sessions#create_anunciar", :as => "log_in_anunciar"

   root :to => "pages#home"

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	
	has_many :vagas
	has_many :perfis

  attr_accessor :password
  before_save :encrypt_password
  
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_presence_of :nome
  

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end


end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  # GET /empresas
  # GET /empresas.xml
	
	respond_to :html, :xml
	
	def meusdados
		@empresa = Empresa.find(session[:user_id])
		@vagas = @empresa.vagas.order("created_at DESC").page(params[:page]).per(12)

		respond_to do |format|
			format.html {render :show }
			format.xml  { render :xml => @empresas }
		end
	end

  def index
    @empresas = Empresa.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @empresas }
    end
  end

  # GET /empresas/1
  # GET /empresas/1.xml
  def show
	@empresa = Empresa.find(params[:id])
	#@vagas = @tag.vagas.order("created_at DESC").page(params[:page]).per(8)
	@vagas = @empresa.vagas.order("created_at DESC").page(params[:page]).per(10)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @empresa }
    end
  end

  # GET /empresas/new
  # GET /empresas/new.xml
  def new
    @empresa = Empresa.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @empresa }
    end
  end

  # GET /empresas/1/edit
  def edit
    @empresa = Empresa.find(params[:id])
  end

  # POST /empresas
  # POST /empresas.xml
  def create
    @empresa = Empresa.new(params[:empresa])
	
    respond_to do |format|
      if @empresa.save
			session[:user_id]=@empresa.id
        format.html { redirect_to(anunciar_url, :notice => 'Cadastrado com Sucesso') }
        format.xml  { render :xml => @empresa, :status => :created, :location => @empresa }
      else
        format.html { redirect_to anunciar_url, :notice=>"Preencha o formulário corretamente" }
        format.xml  { render :xml => @empresa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.xml
  def update
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      if @empresa.update_attributes(params[:empresa])
        format.html { redirect_to(@empresa, :notice => 'Empresa was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @empresa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.xml
  def destroy
    @empresa = Empresa.find(params[:id])
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to(empresas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_estatisticas.html.erb
<h1>Estatisticas</h1>
<ul>
	<% Perfil.all.each do |p| %>
	<% vagas = Vaga.vagas(p.id, @empresa.id) %>
		<% if vagas.size > 0 %>
			<% if p.nome=="Todos" %>
			<li>	<%= "#{pluralize(vagas.size, "vaga")} para"%>
					<%= link_to " #{p.nome} Perfis",empresa_perfil_vagas_path(@empresa, p.id)%> </li>
			<% else %>
			<li>	<%= "#{pluralize(vagas.size, "vaga")} para"%>
					<%= link_to " #{p.nome}", empresa_perfil_vagas_path(@empresa, p.id) %> </li>
			<% end %>
		<% end %>
	<% end %>
</ul>

app/views/empresas/_form.html.erb
<%= simple_form_for(@empresa) do |f| %>
  <div class="inputs">
    <%= f.input :nome %>
    <%= f.input :email %>
	 <%= f.input :password %>	
	<p>
		 <%= f.label 'Empresa' %>
		 <%= f.text_area :sobre_a_empresa, :rows=>2, :cols=>40 %>
	</p>
  </div>

  <div class="actions">
	<%= f.button :submit, 'Cadastrar', :class=>"botao"%>
  </div>
<% end %>

app/views/empresas/_lateral.html.erb
<div id="dados_cadastrais" class="round">
	<%= render :partial=>'empresas/meusdados' %>
</div>
<div id="estatisticas">
	<%= render :partial =>'empresas/estatisticas'%>
</div>

app/views/empresas/_meusdados.html.erb
<% if current_user %>
	<h1>Seus dados Cadastrais</h1><div class="clear"></div>
<% else %>
	<h1>Dados do Responsavel</h1><div class="clear"></div>
<% end %>

<p>
  <b>Nome:</b>
  <span class="dado"><%= @empresa.nome %><span class="dado">
</p>

<p>
  <b>Email:</b>
  <span class="dado"><%= @empresa.email %><span class="dado">
</p>
<p>
  <b>Empresa:</b>
  <span class="dado"><%= @empresa.nome_empresa %><span class="dado">
</p>
<div id="info">
	<b>Sobre a Empresa:</b> <br />
	<%= @empresa.sobre_a_empresa %>
</div>
<% if can_edit_dados(@empresa.id) %>
<span class="editar">
	<%= link_to 'Editar Dados', edit_empresa_path(@empresa) %>
</span>
<% end %>

app/views/empresas/_vaga.html.erb
<div class="<%= cycle("even","odd")%> vaga">
	<div class="info">
		<p><%= vaga.updated_at.to_date.to_formatted_s(:long) %></p>
		<p>Cid.: <%= vaga.cidade %></p>
		<p>
			<% if vaga.perfil.nome == "Todos" %>
			<b>Vaga para <%= vaga.perfil.nome %></b>
			<% else %>
			<b><%= vaga.perfil.nome %></b>
			<% end %>
		</p>
	</div>
	<div class="detalhes">
		<p class="titulo_vaga"><%=vaga.vaga%>
			<% if can_edit_dados(vaga.empresa_id) %>			
			<span class="right">
				<%= link_to "FINALIZAR", vaga, :method=>:delete, 
					:confirm =>"Tem certeza que deseja eliminar a vaga?", :class=>"titulo_vaga" %>|
				<%= link_to "EDITAR", edit_vaga_path(vaga), :class=>"titulo_vaga" %>
			</span>
			<% end %>
		</p>
		<p><%= vaga.vaga_curta %></p>
	</div>
</div>

app/views/empresas/edit.html.erb
<h1>Editing empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |

app/views/empresas/index.html.erb
<h1>Listing empresas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Sobre a empresa</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @empresas.each do |empresa| %>
  <tr>
    <td><%= empresa.nome %></td>
    <td><%= empresa.email %></td>
    <td><%= empresa.sobre_a_empresa %></td>
    <td><%= link_to 'Show', empresa %></td>
    <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
    <td><%= link_to 'Destroy', empresa, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>New empresa</h1>

<%= render :partial=>'form', :locals => { :edit => false } %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<div id="conteudo"> 

	<h1 class="vagas_recentes">Vagas Cadastradas <%= @empresa.vagas.size %></h1>
	<!-- VAGAS -->
	<p class="paginacao">
		<%= paginate @vagas %>
	</p>
	<% @vagas.each do |vaga| %>
		<%= render :partial=>'vaga', :locals=>{:vaga=>vaga} %>
	<% end %>
	<!-- FIMMMM VAGAS -->
	<p class="paginacao">
		<%= paginate @vagas %>
	</p>

</div>
<div id="lateral">
	<%= render :partial=>'empresas/lateral' %>
</div>
<div id="clear">
</div>